### PR TITLE
Fix doxygen namespace generation for brain

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by hernando** [comment]
Moving the file lists form files.cmake to CMakeLists.txt is something that Daniel suggested before, but I didn't change it because Brion has a files.cmake. For consistency it should be the same in both libraries.

**Comment by eile** [comment]
(sigh) incremental vs. global changes again. I'll do it for Brain to, although imo this is not a reason to block the PR.

**Comment by eile** [comment]
Just saw your PR.

**Comment by eile** [comment]
+1 then?

**Comment by hernando** [comment]
Too quick complaining ;)

**Comment by eile** [comment]
Asking! ;)

**Comment by hernando** [comment]
Sometimes I think that reviewers comments could be addressed with PRs on the original PR like in this case. This will save time because explaining the requested changes sometimes is even longer than directly doing them (e.g. typos). We should discuss this approach.

**Pull request merged**
