### PR TITLE
Resolve MVDTool via find_package() for Nix support

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by tribal-tec** [comment]
retest this please

**Comment by hernando** [comment]
No that I realize, shouldn't you add MVDTool to target_link_libraries even if it's header only.

**Comment by tribal-tec** [comment]
It's there in brain/CMakeLists.txt:51

**Comment by hernando** [comment]
Yes you're right.

**Comment by tribal-tec** [comment]
retest this please

**Pull request merged**
