### PR TITLE
Add python 3.4 to wheel build

### PR DESCRIPTION
**Pull request by hernando**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Sorry for the inconvenience, but the build is failing due to [HELP-7886](https://bbpteam.epfl.ch/project/issues/browse/HELP-7886)

**Comment by hernando** [comment]
That's the only Python3 version that we have available in the cluster at the moment, that's the reason.

**Comment by hernando** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Pull request merged**
