### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by mgeplf**
* Fix TOC showing up
* fix Changelog reference

### CODE REVIEW

**Comment by bilgili** [comment]
+1

**Comment by eile** [comment]
fix Changelog reference might break doxygen.

**Comment by mgeplf** [comment]
is the README.md machine generated? Or is it used in generating other doc?

**Comment by rdumusc** [comment]
Is is used for the doxygen main page as well I think: http://bluebrain.github.io/Brion-1.7/index.html

**Comment by mgeplf** [comment]
I see.  In that case, I guess it's up to you how you want to handle it.  I just found that when I landed on the main page, the changelog link wasn't working, so I tried to fix it.

I'll close this down, and let you guys decide how best to handle it.

**Pull request closed without merging**
