### PR TITLE
Fix data_converter of std::vector of vmml::vector

### PR DESCRIPTION
**Pull request by alkino**
With HighFive v2.2 signature of data_converter has changed.

### CODE REVIEW

**Comment by NadirRoGue** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
CI configured to use  **brion_hf** spack branch.

**Comment by ppodhajski** [comment]
retest this please

**Comment by ppodhajski** [comment]
retest this please

**Pull request merged**
