### PR TITLE
Properly declare leaking Boost

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by tribal-tec** [comment]
FYI @hernando

**Comment by rdumusc** [comment]
But is boost leaking? I see: list(APPEND BRION_DEPENDENT_LIBRARIES Lunchbox vmmlib)

**Comment by tribal-tec** [comment]
Yes it is. Good catch! I wanted to doublecheck if this variable was set correctly.

**Comment by rdumusc** [comment]
+1

**Pull request merged**
